### ISSUE TITLE
More .NET/C# resources

### ISSUE THREAD

**Issue by nour-nagm** [Eyadhamza/Eng-Hammad-Recommendations#1]
### Eng. Hammad also mentioned these books in this [post](https://www.facebook.com/mohamed.hamedhammad/posts/5345089308896909): 
- C# 9.0 in a Nutshell 
- C# in Depth
- ~Concurrency in .NET~ 

### he also mentioned Gavin Lon's [Advanced C#](https://www.youtube.com/playlist?list=PL4LFuHwItvKaOi-bN1E2WUVyZbuRhVokL) playlist (good channel overall, Gavin Lon also provides beginners C# playlist) - but I don't have the post link.

**Comment by Eyadhamza** [comment]
Thank you for providing the resources..
they are now added
